# Run tests

name: CI

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Symbulation
        uses: actions/checkout@v2
        with:
          path: SymbulationEmp

      - name: Checkout Empirical
        uses: actions/checkout@v2
        with:
          repository: devosoft/Empirical
          path: Empirical
          submodules: "recursive"

      - name: run symbulation
        run: cd SymbulationEmp && make debug && ./symbulation

      # Runs a single command using the runners shell
      - name: Make tests
        run: cd SymbulationEmp && make coverage
        
      - name: Generate coverage
        run: cd SymbulationEmp && gcov -abcfu main.cc
        
      - name: Upload coverage
        uses: codecov/codecov-action@v1.5.2
        with:
          root_dir: SymbulationEmp
